### PR TITLE
Fixed the toggleFlash for iOS

### PR DESCRIPTION
**Pull request by adlanarifzr**
Fully tested on iPhone

### CODE REVIEW

**Comment by akasiid** [comment]
Crashed on iphones, tested 5c, 5s and X. Can you check?

**Comment by adlanarifzr** [comment]
Can you share logs when it crashed?

**Comment by akasiid** [comment]
Nothing. Just blink once. And "Lost connection to device.".

**Comment by warriorCoder** [comment]
Also, get a crash on iPhone 6s running iOS 12.1.4
The error I get is: Runner[805/0x10612eb80] [lvl=3] +[GMVx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.

and

io.flutter.1.gpu (10): EXC_BAD_ACCESS (code=1, address=0x6e2cf1cf0)

**Comment by warriorCoder** [comment]
I figured out the issue. The problem is on line 309 of the QrMobileVisionPlugin.m file.
Remove the _reader = nil; line as we don't want to dispose of the reader, just turn the flash on or off.

**Comment by gmiquilena1** [comment]
Hi, when the feature will is on production??? Thanks

**Comment by rmtmckenzie** [comment]
integrated #189 instead.

**Pull request closed without merging**
