### PR TITLE
Use flutter's permissions handler rather than permissions activity (fixes #27)

### LINKED ISSUE #27: Crash 0.0.5 on Android first permission result or permission denied
The plugin (so as the all app) is crashing the first time when we accept the permission or when we refuse the permission:

```
I/System.out( 6468): REQUESTING PERMISSIONS
I/flutter ( 6468): [INFO] LoggingMiddleware: {Action: CashRegisterModeChangedAction  = CashRegisterMode.scan, State: cart=amount=0.0, items=[], cash_register=amount=, quantity=1, product=null, amountLabel=$0.00, mode=CashRegisterMode.scan, merchantState=MerchantState{merchant: Instance of 'Merchant'}, ts: 2018-07-20 08:37:47.241297}
D/EGL_emulation( 6468): eglMakeCurrent: 0xea0e0be0: ver 3 0 (tinfo 0xe8611e40)
I/System.out( 6468): onRequestPermissionsResult
I/System.out( 6468): CAMERA_PERMISSIONS_REQUEST
I/System.out( 6468): Granted
I/System.out( 6468): PERMISSIONS WERE GRANTED
I/CameraManagerGlobal( 6468): Connecting to camera service
W/c.g.r.QrMobVisPlugin( 6468): Starting QR Mobile Vision failed
W/c.g.r.QrMobVisPlugin( 6468): java.lang.NullPointerException: Attempt to read from field 'com.github.rmtmckenzie.qrmobilevision.QRReader com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.reader' on a null object reference
W/c.g.r.QrMobVisPlugin( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.started(QrMobileVisionPlugin.java:134)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.continueStarting(QRReader.java:102)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.access$000(QRReader.java:14)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader$1.permissionsGranted(QRReader.java:70)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.github.rmtmckenzie.qrmobilevision.PermissionsActivity.onRequestPermissionsResult(PermissionsActivity.java:56)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.os.Looper.loop(Looper.java:193)
W/c.g.r.QrMobVisPlugin( 6468): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/c.g.r.QrMobVisPlugin( 6468): 	at java.lang.reflect.Method.invoke(Native Method)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/c.g.r.QrMobVisPlugin( 6468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/AndroidRuntime( 6468): Shutting down VM
E/AndroidRuntime( 6468): FATAL EXCEPTION: main
E/AndroidRuntime( 6468): Process: com.kiwi.merchant.kiwimobile, PID: 6468
E/AndroidRuntime( 6468): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=123, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.kiwi.merchant.kiwimobile/com.github.rmtmckenzie.qrmobilevision.PermissionsActivity}: java.lang.NullPointerException: Attempt to read from field 'io.flutter.plugin.common.MethodChannel$Result com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.startResult' on a null object reference
E/AndroidRuntime( 6468): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime( 6468): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime( 6468): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 6468): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 6468): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 6468): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime( 6468): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6468): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6468): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 6468): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6468): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 6468): Caused by: java.lang.NullPointerException: Attempt to read from field 'io.flutter.plugin.common.MethodChannel$Result com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.startResult' on a null object reference
E/AndroidRuntime( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.startingFailed(QrMobileVisionPlugin.java:154)
E/AndroidRuntime( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.continueStarting(QRReader.java:104)
E/AndroidRuntime( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader.access$000(QRReader.java:14)
E/AndroidRuntime( 6468): 	at com.github.rmtmckenzie.qrmobilevision.QRReader$1.permissionsGranted(QRReader.java:70)
E/AndroidRuntime( 6468): 	at com.github.rmtmckenzie.qrmobilevision.PermissionsActivity.onRequestPermissionsResult(PermissionsActivity.java:56)
E/AndroidRuntime( 6468): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
E/AndroidRuntime( 6468): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
E/AndroidRuntime( 6468): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime( 6468): 	... 11 more
I/Process ( 6468): Sending signal. PID: 6468 SIG: 9

```

Tested on Android emulator API 28

### PR DESCRIPTION
**Pull request by jaumard**
So I remove the PermissionActivity has it's not needed and can be handled by the registrar. 
Also fix #27 by not reseting the readingInstance is we're waiting for permission result.

Works on the example app and my own :) let me know what you think

### CODE REVIEW

**Comment by rmtmckenzie** [comment]
Looks great for the most part, although this has made me realize that my IDE settings aren't saved into the project (and therefore it uses your defaults which are different than mine...). So I'll just adopt these changes into a commit and reformat back to how it was. But thanks though, this is a cleaner solution! The permissions activity is a remnant of when this was residing in my app rather than in the plugin and it was easier to use a new activity than add to the existing flutter activity.

**Comment by jaumard** [comment]
Yeah I notice that the formatting was different, don't hesitate to put a .editorconfig with your formatting inside ^^ if I can I'll help more in the future it will be better to have same formatting style

**Comment by rmtmckenzie** [comment]
I'm just working on merging your changes + a few other fixes I had ready to go, and I'm including an editorconfig =).

**Comment by rmtmckenzie** [comment]
This code has been integrated into the main branch. Thanks for the help =).

**Pull request closed without merging**
