### PR TITLE
Fix FPS on iOS by switching to iOS native barcode scanning

### PR DESCRIPTION
**Pull request by shkatulo**
Fix FPS on iOS, but now min supported iOS version is 9.0

### CODE REVIEW

**Comment by alexisnaud** [comment]
thanks !

**Comment by qimingweng** [comment]
Have not tried this but according to #56 this seems to solve an FPS issue that I am also seeing. Is there any possibility of merging this? Targeting 8.0 is quite low, even the latest Google Maps libraries for iOS target 9.0.

**Comment by qimingweng** [comment]
Any update on this pull request?

**Comment by lovelessX** [comment]
I attempted to use this change on my local build and while it did fix the FPS issue, it made the barcode scanning way less effective - in fact I couldn't get it to scan any of my previous samples that worked with the original Google implementation.

**Comment by booooza** [comment]
Tested this PR on a physical iPhone 6 device and can confirm that the laggy camera preview has gone away. Also I couldn't notice any notable decrease in barcode detection efficiency. @shkatulo thanks for the work! 👍

**Comment by rmtmckenzie** [comment]
This should be resolved by the switch to FirebaseMobileVision and I would prefer to keep the plugin using that for now since it's right in the name and it'll have similar performance to android. Thanks for the work done here though!

**Pull request closed without merging**
